"""empty message

Revision ID: 3b971d32f357
Revises: c01fdeee819f
Create Date: 2022-07-24 15:43:12.193662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b971d32f357'
down_revision = 'c01fdeee819f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('c_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'c_id')
    # ### end Alembic commands ###
