"""empty message

Revision ID: 6e96816841af
Revises: 97bf808e0ce4
Create Date: 2022-07-17 15:01:00.744821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e96816841af'
down_revision = '97bf808e0ce4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('o_name', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'o_name')
    # ### end Alembic commands ###
