"""empty message

Revision ID: f6a094ed755b
Revises: 79c5952f4ab6
Create Date: 2022-07-22 11:57:11.777033

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f6a094ed755b'
down_revision = '79c5952f4ab6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('question_ibfk_2', 'question', type_='foreignkey')
    op.drop_column('question', 'course_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('course_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('question_ibfk_2', 'question', 'course', ['course_id'], ['id'])
    # ### end Alembic commands ###
