"""empty message

Revision ID: ffa93c58eb3b
Revises: 3b971d32f357
Create Date: 2022-07-27 20:12:55.417296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffa93c58eb3b'
down_revision = '3b971d32f357'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('likes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('answer', 'likes')
    # ### end Alembic commands ###
